export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const HAS_ERROR = 'HAS_ERROR';

export const AUTH = {
  LOGIN: 'AUTH_LOGIN',
  REGISTER: 'AUTH_REGISTER',
  LOGOUT: 'AUTH_LOGOUT'
};

export const CATEGORY = {
  GET_ALL: 'CATEGORY_GET_ALL',
  GET_ONE: 'CATEGORY_GET_ONE',
  CREATE: 'CATEGORY_CREATE',
  UPDATE: 'CATEGORY_UPDATE',
  DELETE: 'CATEGORY_DELETE'
};

export const BRAND = {
  GET_ALL: 'BRAND_GET_ALL',
  GET_ONE: 'BRAND_GET_ONE',
  CREATE: 'BRAND_CREATE',
  UPDATE: 'BRAND_UPDATE',
  DELETE: 'BRAND_DELETE'
};

export const DISCOUNT = {
  GET_ALL: 'DISCOUNT_GET_ALL',
  GET_ONE: 'DISCOUNT_GET_ONE',
  CREATE: 'DISCOUNT_CREATE',
  UPDATE: 'DISCOUNT_UPDATE',
  DELETE: 'DISCOUNT_DELETE'
};

export const PRODUCT = {
  GET_ALL: 'PRODUCT_GET_ALL',
  GET_ONE: 'PRODUCT_GET_ONE',
  CREATE: 'PRODUCT_CREATE',
  UPDATE: 'PRODUCT_UPDATE',
  DELETE: 'PRODUCT_DELETE',
  CREATE_VARIANT: 'PRODUCT_CREATE_VARIANT',
  UPDATE_VARIANT: 'PRODUCT_UPDATE_VARIANT',
  DELETE_VARIANT: 'PRODUCT_DELETE_VARIANT'
};

export const USER = {
  GET_ALL: 'USER_GET_ALL',
  GET_ONE: 'USER_GET_ONE',
  CREATE: 'USER_CREATE',
  UPDATE: 'USER_UPDATE',
  DELETE: 'USER_DELETE'
};

export const IMAGE = {
  UPLOADING: 'IMAGE_UPLOADING',
  UPLOAD_SINGLE: 'IMAGE_UPLOAD_SINGLE',
  UPLOAD_MULTI: 'IMAGE_UPLOAD_MULTI'
};
