@startuml fpt_related_product
!theme cerulean

actor       User       as u
participant FptRecommendationPlatform as f
participant Client as c
participant Server as s
participant Database as d

alt at 02:00 AM
s -> d: GetListProduct()
d -> s: Result()
s -> f: UpdateNewData()
end

alt at 03:00 AM
f -> f: Train model with new data
end


u -> c: Xem sản phẩm
c -> f: GetRecommendedRelatedItem(productId)

alt Fpt No Response
  f -> c: < No content >
  c -> u: Ẩn mục sản phẩm liên quan trên giao diện

else Fpt Response Data
  f -> c: listProductId (related to the sent productId)

  c -> s: GetProductById(listProductId)
  s -> d: QueryToFind()
  d -> s: Result()

  alt Không tìm thấy hoặc sản phẩm bị ẩn/xóa/bán hết
    s -> c: ErrorResponse()
    c -> u: Ẩn mục sản phẩm liên quan trên giao diện
  else Tìm thấy danh sách sản phẩm theo id
    s -> c: SuccessResponse()
    c -> u: Hiển thị danh sách sản phẩm liên quan
  end
end

@endumc