@startuml 06_edit_profile
!theme cerulean

actor       User       as u
participant LoginPage as lp
participant AccountPage as ap
participant Server as s
participant Database as d

alt Đã đăng nhập
  u -> ap: Quản lý Địa chỉ
  ap -> s: Request()
  s -> d: Query()
  d -> s: Result()

  alt Lấy danh sách thành công
    s -> ap: SuccessResponse()
    ap -> u: Hiển thị danh sách địa chỉ
  else Lấy danh sách thất bại
    s -> ap: ErrorResponse()
    ap -> u: Hiển thị lỗi
  end
else Chưa đăng nhập
  u -> lp: Chuyển đến trang Đăng nhập
end


@enduml
