@startuml 07_login
!theme cerulean

actor       User       as u
participant LoginPage as lp
participant Server as s
participant Database as d
participant LocalStorage as ls

u   -> lp: Nhập thông tin\nClick "Đăng nhập"
lp  -> lp: ValidateInput()

lp  -> s: Request()
s   -> d: Query()
d   -> s: Result()

alt Thông tin chính xác
  s   -> lp: SuccessResponse()
  lp  -> ls: SaveAccessToken()
  lp  -> u: Chuyển đến trang chủ
else Thông tin sai
  s   -> lp: ErrorResponse()
  lp  -> u: Thông báo lỗi
end

@enduml
