@startuml 09_change_password
!theme cerulean

actor       User       as u
participant ChangePassForm as cpf
participant AccountPage as ap
participant Server as s
participant Database as d

u   -> ap: Đổi mật khẩu
ap  -> cpf: Invoke()
cpf -> u: Hiển thị form nhập password
u   -> cpf: Nhập mật khẩu hiện tại\nvà mật khẩu mới
cpf -> cpf: ValidateInput()
cpf -> ap: SendData()
ap  -> s: Request()
s   -> d: Query()
d   -> s: Result()

alt Thành công
  s   -> ap: SuccessResponse()
  ap  -> u: Thông báo đổi mật khẩu thành công
else Thất bại
  s   -> ap: ErrorResponse()
  ap  -> u: Thông báo lỗi
end

@enduml
