@startuml delete category
!theme cerulean

actor       User       as u
participant LoginPage as lp
participant DashboardPage as dash
participant Server as s
participant Database as d

alt Đăng nhập với tài khoản admin
  u -> dash: Quản lý Danh mục
  dash -> s: Request()
  s -> d: Query()
  d -> s: Result()

  alt Lấy danh sách thành công
    s -> dash: SuccessResponse()
    dash -> u: Hiển thị danh sách danh mục
    u -> dash: Chọn danh mục cần xóa
    dash -> s: RequestDelete()
    s -> d: QueryDelete()
    d -> s: Result()

    alt Xóa thành công
      s -> dash: SuccessResponse()
      dash -> u: Hiển thị danh sách danh mục
    else Xóa thất bại
      s -> dash: ErrorResponse()
      dash -> u: Hiển thị lỗi
    end

  else Lấy danh sách thất bại
    s -> dash: ErrorResponse()
    dash -> u: Hiển thị lỗi
  end
else Chưa đăng nhập
  u -> lp: Chuyển đến trang Đăng nhập
end


@enduml