@startuml view category list
!theme cerulean

actor       User       as u
participant LoginPage as lp
participant DashboardPage as dash
participant Server as s
participant Database as d

alt Đăng nhập với tài khoản admin
  u -> dash: Quản lý Danh mục
  dash -> s: Request()
  s -> d: Query()
  d -> s: Result()

  alt Lấy danh sách thành công
    s -> dash: SuccessResponse()
    dash -> u: Hiển thị danh sách danh mục
  else Lấy danh sách thất bại
    s -> dash: ErrorResponse()
    dash -> u: Hiển thị lỗi
  end
else Chưa đăng nhập
  u -> lp: Chuyển đến trang Đăng nhập
end


@enduml