@BASE_URL = http://localhost:3001/api/v1
@RESOURCE = auth


POST {{BASE_URL}}/{{RESOURCE}}/register
content-type: application/json

{
    "firstName":"ddsf",
    "lastName":"fdsfsdfsd",
    "phone":"0123456689",
    "email":"admdin@hk.com",
    "password":"12"
}

####


POST {{BASE_URL}}/{{RESOURCE}}/login
content-type: application/json

{
  "username": "sssssss@nf.com",
  "password": "hello123"
}

###


@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTg1NGQ2M2YyYjNkMjczZDNhZTFkMTMiLCJpYXQiOjE2MzYxODc1MDIsImV4cCI6MTYzNjc5MjMwMn0.LBECdSK_t6jnqW5zYL9XYQtLgFkamThc6VckD65P3ig

@RF_TOKEN = 2c527af0d66f99b4aea24dee6c409e5618870c2a07df2692541460ec26515b0da2e9ce2e17a3efbb3f1d4373ee80f658cafa97c6cde9ca3cf0525eb64e67a3c5

POST {{BASE_URL}}/{{RESOURCE}}/refresh-token
Content-Type: application/json

{
  "refreshToken":"{{RF_TOKEN}}"
}

###

POST {{BASE_URL}}/{{RESOURCE}}/logout
Content-Type: application/json

{
  "refreshToken":"{{RF_TOKEN}}"
}

###

GET {{BASE_URL}}/me
authorization: Bearer {{TOKEN}}

###