@BASE_URL = http://localhost:3001/api/v1
@RESOURCE = categories

GET {{BASE_URL}}/{{RESOURCE}}

###

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTdlM2U0YmUxYTQ3NjhiMjdkOTBjMDAiLCJmaXJzdE5hbWUiOiJLaMOhbmgiLCJsYXN0TmFtZSI6IkzDom0iLCJmdWxsTmFtZSI6Iktow6FuaCBMw6JtIiwiZ2VuZGVyIjoiT1RIRVIiLCJlbWFpbCI6InNzc3Nzc0BuZi5jb20iLCJwaG9uZSI6IjAxMjUyNTY3ODkiLCJ1c2VybmFtZSI6IiIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ZmFsc2UsImNyZWF0ZWRBdCI6IjIwMjEtMTAtMzFUMDY6NTc6MTUuMjQ1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMTAtMzFUMDY6NTc6MTUuMjQ1WiIsImlkIjoiNjE3ZTNlNGJlMWE0NzY4YjI3ZDkwYzAwIiwiaWF0IjoxNjM2MDg1NzA4LCJleHAiOjE2MzY2OTA1MDh9.-FQoGH9Foti3wuOVAwbLeiItjy1Jq3sM_BiC9LpFrdI

POST {{BASE_URL}}/{{RESOURCE}}
authorization: Bearer {{TOKEN}}
content-type: application/json

{
   "name": "test ssss",
   "desc": "Hello"
}

####